#!/bin/sh
# HOME_CSS_BUNDLE (Gil, 2026-09-09): the homepage links one stylesheet for its
# section modules instead of thirteen, and links it at the top of <head> so
# the browser discovers it from the first bytes. Run this after editing any
# of the files below, then bump ?v=home… in index.html.
cd "$(dirname "$0")/.." || exit 1
FILES="assets/workflow-transformation.css assets/phase2-motion.css assets/hub-links.css assets/software-band.css assets/outcomes-stack.css assets/how-steps.css assets/homepage-spine.css assets/reveal.css assets/rail.css assets/explainer-clips.css assets/tcs-type.css assets/tcs-footer.css"
{
  echo "/* Generated by tools/build-home-css.sh. Do not edit; edit the section files and rebuild. */"
  for f in $FILES; do echo; echo "/* ==== $f ==== */"; cat "$f"; done
} > assets/home.css
wc -c assets/home.css
